# Generated by Django 3.2.7 on 2021-10-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211005_0959'),
        ('api', '0004_auto_20211005_1351'),
        ('api', '0004_auto_20211005_1425'),
    ]

    operations = [
    ]
