# Generated by Django 3.2.7 on 2021-10-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20211005_1736"),
        ("api", "0006_auto_20211005_1822"),
    ]

    operations = []
