# Generated by Django 3.2.7 on 2021-10-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_instructor'),
        ('api', '0010_alter_lesson_student'),
    ]

    operations = [
    ]
