# Generated by Django 3.2.7 on 2021-10-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_practicelog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicelog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="practicelog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
