# Generated by Django 3.2.8 on 2021-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20211012_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="upload",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
