# Generated by Django 3.2.8 on 2021-10-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211016_1443'),
        ('api', '0021_auto_20211016_1243'),
    ]

    operations = [
    ]
