# Generated by Django 3.2.8 on 2021-10-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_email'),
        ('api', '0024_auto_20211018_1632'),
    ]

    operations = [
    ]
